name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'    
      - name: Install software
        run: sudo apt-get install -y chromium-browser ffmpeg  xvfb
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium webdriver-manager pyvirtualdisplay mailtm vosk ibm_cloud_sdk_core ibm_watson imap_tools mimesis TwoCaptcha undetected_chromedriver==3.1.5.post4 urlextract pydub SpeechRecognition fake_useragent stem
      

      - name: Running the Python script
        run: python sign_up.py
        
      - name: Commit and Push The Results From Python Selenium Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "GitHub Actions Results added"
         git push
